// Writes the guide's system prompt next to the API function, so the function doesn't have to
// import the site's source files at runtime. Runs before every build.
import { writeFileSync } from 'node:fs';
import { GUIDE_SYSTEM_PROMPT } from '../src/data/knowledge.ts';

writeFileSync(
  new URL('../api/_prompt.ts', import.meta.url),
  `// Generated by scripts/guide-prompt.mjs from src/data. Edit those files, not this one.\nexport const GUIDE_SYSTEM_PROMPT = ${JSON.stringify(GUIDE_SYSTEM_PROMPT)};\n`,
);
